# The model arguments
model_name: UNet3D
model_kwargs:
  in_channels: 1
  out_channels: 1
  initial_num_fmaps: 32
  fmap_growth: 2
  scale_factor: [[1, 2, 2], [1, 2, 2], 2]
  final_activation: Sigmoid
  conv_type_key: 'vanilla'

training_optimizer_kwargs:
  method: Adam
  lr: 0.0001
  weight_decay: 0.0005

devices:
  - 0
